spring.datasource:
  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: sa

spring.h2.console.enabled: true

camunda.bpm:
  filter:
    create: All Tasks

plugin.identity.keycloak:
  keycloakIssuerUrl: https://id.f4erp.com/auth/realms/dev
  keycloakAdminUrl: https://id.f4erp.com/auth/admin/realms/dev
  clientId: help-desk
  clientSecret: 6df5ecf8-358c-453b-b104-fb495d9a35a3
  useEmailAsCamundaUserId: false
  useUsernameAsCamundaUserId: true
  administratorGroupName: camunda-admin

server.port: 3000

security:
  oauth2:
    client:
      client-id: help-desk
      client-secret: 6df5ecf8-358c-453b-b104-fb495d9a35a3
      accessTokenUri: https://id.f4erp.com/auth/realms/dev/protocol/openid-connect/token
      userAuthorizationUri: https://id.f4erp.com/auth/realms/dev/protocol/openid-connect/auth
      scope: openid profile email
    resource:
      userInfoUri: https://id.f4erp.com/auth/realms/dev/protocol/openid-connect/userinfo
