spring.datasource:
  url: jdbc:postgresql://localhost/helpdesk
  username: postgres
  password:

camunda.bpm:
  process-engine-name: F4ERP
  filter:
    create: All Tasks

#plugin.identity.keycloak:
#  keycloakIssuerUrl: https://id.f4erp.com/auth/realms/dev
#  keycloakAdminUrl: https://id.f4erp.com/auth/admin/realms/dev
#  clientId: help-desk
#  clientSecret: 6df5ecf8-358c-453b-b104-fb495d9a35a3
#  useEmailAsCamundaUserId: true
#  administratorGroupName: camunda-admin

server.port: 3000


#security:
#  oauth2:
#    client:
#      client-id: help-desk
#      client-secret: 6df5ecf8-358c-453b-b104-fb495d9a35a3
#      accessTokenUri: https://id.f4erp.com/auth/realms/dev/protocol/openid-connect/token
#      userAuthorizationUri: https://id.f4erp.com/auth/realms/dev/protocol/openid-connect/auth
#      scope: openid profile email
#    resource:
#      userInfoUri: https://id.f4erp.com/auth/realms/dev/protocol/openid-connect/userinfo
spring:
  jpa:
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true


security.oauth2.resource.id: 'your-firebase-app-id'
