spring.datasource:
  url: jdbc:postgresql://localhost/helpdesk
  username: postgres
  password:

camunda.bpm:
  process-engine-name: F4ERP
  filter:
    create: All Tasks

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

#plugin.identity.keycloak:
#  keycloakIssuerUrl: https://id.f4erp.com/auth/realms/dev
#  keycloakAdminUrl: https://id.f4erp.com/auth/admin/realms/dev
#  clientId: help-desk
#  clientSecret: 6df5ecf8-358c-453b-b104-fb495d9a35a3
#  useEmailAsCamundaUserId: true
#  administratorGroupName: camunda-admin

server.port: 3000

#security:
#  oauth2:
#    client:
#      client-id: help-desk
#      client-secret: 6df5ecf8-358c-453b-b104-fb495d9a35a3
#      accessTokenUri: https://id.f4erp.com/auth/realms/dev/protocol/openid-connect/token
#      userAuthorizationUri: https://id.f4erp.com/auth/realms/dev/protocol/openid-connect/auth
#      scope: openid profile email
#    resource:
#      userInfoUri: https://id.f4erp.com/auth/realms/dev/protocol/openid-connect/userinfo
spring:
  jpa:
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
