spring.datasource:
  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: sa

spring.h2.console.enabled: true

camunda.bpm:
  process-engine-name: F4ERP
  filter:
    create: All Tasks

plugin.identity.keycloak:
  keycloakIssuerUrl: http://localhost:8080/auth/realms/dev
  keycloakAdminUrl: http://localhost:8080/auth/realms/dev/admin
  clientId: account
  clientSecret: f6694ac7-89e0-4ef4-88e8-5eea85c6d6c1
  useEmailAsCamundaUserId: true

server.port: 3000

security:
  oauth2:
    client:
      client-id: account
      client-secret: f6694ac7-89e0-4ef4-88e8-5eea85c6d6c1
      accessTokenUri: http://localhost:8080/auth/realms/dev/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:8080/auth/realms/dev/protocol/openid-connect/auth
      scope: openid profile email
    resource:
      userInfoUri: http://localhost:8080/auth/realms/dev/protocol/openid-connect/userinfo
